topic_modeling_path = './output/topic_modeling/'
google_play_model_path = './output/google_play_categories/models/'
database_path = './input/total-v1.db'
preprocessed_data_path = './output/sampled.csv'
test_input_path = './input/test_input.csv'
test_result_path = './output/test/'
test_models_result_path = './output/test_models_result.txt'
