topic_modeling_path = './output/topic_modeling/'
google_play_model_path = './output/google_play_categories/models/'
preprocessed_data_path = './output/preprocessed.csv'
english_db_data_path = './output/english_db.csv'
database_path = './input/total-v2.db'
test_input_path = './input/test_input.csv'
test_result_path = './output/test/'
test_models_result_path = './output/test_models_result.txt'