model_path = './output/word2vec.model'
topic_modeling_path = './output/topic_modeling/'
google_play_model_path = './output/google_play_categories/models/'
database_path = './input/total-v1.db'
preprocessed_data_path = './output/preprocessed.csv'
test_input_path = './input/test_input.csv'
test_result_path = './output/test/'