topic_modeling_path = './output/topic_modeling/'
google_play_model_path = './output/google_play_categories/models/'
preprocessed_data_path = './output/preprocessed.csv'
english_db_path = './output/english_db.csv'
database_path = './input/total-v2.db'
query_input_path = './input/query/'
query_result_path = './output/query_result/'
best_topic_model_path = './output/best_topic_model/'